apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: theia-volume
  #namespace: ewerton
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage:
        {{- toYaml .Values.configMap.storageSize | "1Gi" }}
